### ISSUE TITLE
作战设置“DQWT*5 HD-4*2 HD-5*1”，只勾选轮询作战，最后仅启动。发现打到HD-5后，会一直重复打HD-5，停不下来。有没办法按照我设置就流程，实现打完最后一关就不打呢？

### ISSUE THREAD

**Issue by sd133cn** [tkkcc/arknights#10]

**Comment by tkkcc** [comment]
DQWT是剿灭，打满就跳过，正常5次就已经打满了。
正常应该是在hd-5与hd-4之前循环，但是如果hd-4导航失败两次，也会被跳过。
之后就只有hd-5能打，所以会一直打hd-5。

只能打到理智空。

**Comment by sd133cn** [comment]
> 

我想按照顺序，打完HD-5就结束，要怎么设置？我关闭轮询作战后，直接就不打了。

**Comment by sd133cn** [comment]
> DQWT是剿灭，打满就跳过，正常5次就已经打满了。 正常应该是在hd-5与hd-4之前循环，但是如果hd-4导航失败两次，也会被跳过。 之后就只有hd-5能打，所以会一直打hd-5。
> 
> 只能打到理智空。

**Comment by sd133cn** [comment]
> DQWT是剿灭，打满就跳过，正常5次就已经打满了。 正常应该是在hd-5与hd-4之前循环，但是如果hd-4导航失败两次，也会被跳过。 之后就只有hd-5能打，所以会一直打hd-5。
> 
> 只能打到理智空。

我想打HD-4 4次，再打HD-5 1次，就结束，该怎么设置？

**Comment by tkkcc** [comment]
不行，只能打到理智空

**Comment by sd133cn** [comment]
> 不行，只能打到理智空

能加个实现这个功能的可选开关吗？T_T

**Comment by tkkcc** [comment]
可以加个关键词，看到就退出作战任务。但是hd-4导航失败你有确认吗。

**Comment by sd133cn** [comment]
> 可以加个关键词，看到就退出作战任务。但是hd-4导航失败你有确认吗。

上面我只是举了个例子，实际上之前我第一次用的时候中间填的不是HD-4，我也记得不清了。这个问题先当不存在吧，有情况我再联络。

**Comment by tkkcc** [comment]
用 break 来退出轮次作战，比如 hd-5*2 break。
