### ISSUE TITLE
贸易站的拉德组合，没德克萨斯会选拉普兰德和铎铃，导致效率下降

### ISSUE THREAD

**Issue by adcchuap** [tkkcc/arknights#109]

**Comment by tkkcc** [comment]
录屏发下

**Comment by adcchuap** [comment]
没录屏，刚才是选了拉德和铎铃，还选过别的空弦伺夜铎铃，铎铃只减心情消耗，不加效率的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月19日(周日) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tkkcc/ArkLights] 贸易站的拉德组合，没德克萨斯会选拉普兰德和铎铃，导致效率下降 (Issue #109)




 
录屏发下

**Comment by tkkcc** [comment]
云手机卡的时候，翻页时会误选中干员，这个没有继续优化。如果是流畅的机子出现这种情况，应该可以复现，建议录屏。

**Comment by adcchuap** [comment]
应该是故意选的，并非翻页误选中，主要是出现很多次了（铎铃也不加效率



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月20日(周一) 下午2:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tkkcc/ArkLights] 贸易站的拉德组合，没德克萨斯会选拉普兰德和铎铃，导致效率下降 (Issue #109)




 
云手机卡的时候，翻页时会误选中干员，这个没有继续优化。如果是流畅的机子出现这种情况，应该可以复现，建议录屏。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 
  	
 	 		  			从QQ邮箱发来的超大附件 		 	
 	 		  	 	 		 			 		
 		 			 VID20230222162902.mp4 (79.37M, 2023年3月24日 16:40 到期) 			 			 				进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=9d9b5f379e567165afe8173767656536cd80cc3365656536474b5804065c5003505614065d04031b56025854480455035049005154515d0751020c0107077036342d7d055557560650560b0653575c06504a54475171d027ea0722fa576b8be230a7c4a8632d09a4f328&t=exs_ftn_download&code=bd97eee6 			
 		
 	
 
  	 	 		 			 		
 		 			 IMG20230222163101.jpg (4.70M, 无限期) 			 			 				进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=c7cc51359a037564f5bf1935633061372f777c35613061371d1c0f510755530e5e071a560502561a0c0054034c52000e0e1e0e57560353510804030004517437717e7007510252070a01050457035007091d5d45062443ddc8326229594e596aa1dffbeb9004469ba30c&t=exs_ftn_download&code=8375a0a7 			
 		
 	
 
  	 	 		 			 		
 		 			 IMG20230222163129.jpg (4.99M, 无限期) 			 			 				进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=ce9b5037ce527164fce81837376165379dab793735616537144b535201545d07575c1b525402521a0550550018005553004954010d045007065c06540056703778297105055356070356040603525405084a5c4752755451c1c6688976e7243ea4520581499402544570&t=exs_ftn_download&code=1d675ae7

**Comment by Justccerly** [comment]
是故意选的，不是翻页卡住了，而且不限于拉德。好像只要有铎铃几乎必选？我上传了录屏，不知道能不能看到。

**Comment by tkkcc** [comment]
没看到录屏啊 @Justccerly

**Comment by Justccerly** [comment]
这里好像上传不了。我上传到阿里云盘了，复制链接就能直接看，麻烦看一下吧。[录屏文件](RPReplay_Final1677246872.mp4 https://www.aliyundrive.com/s/LYyyHCooGG9) @tkkcc

**Comment by tkkcc** [comment]
@Justccerly 确实是bug。你在频道或群里吗，方便提供下账密吗，我没铎铃调试不了。
还有确认下标题日期是最近的，不是很早以前的，之前有次更新把热更禁了。

**Comment by Justccerly** [comment]
> @Justccerly 确实是bug。你在频道或群里吗，方便提供下账密吗，我没铎铃调试不了。
> 还有确认下标题日期是最近的，不是很早以前的，之前有次更新把热更禁了。

频道和群都在，群里私聊谁？热更禁了后频道有人发消息让清空数据，所以我的是最新的。

**Comment by tkkcc** [comment]
群主

**Comment by tkkcc** [comment]
原因是缺了铎铃的基建图标。还出现再说。
