### ISSUE TITLE
大佬有考虑过加个能选骰子队的选项吗，这样就能刷指路鳞了

### ISSUE THREAD

**Issue by czt945** [tkkcc/arknights#126]
求求了，孩子真的刷不出来指路鳞啊

**Comment by DazeCake** [comment]
水月相关功能只为了等级和投资设计

**Comment by czt945** [comment]
好吧😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月17日(周五) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tkkcc/ArkLights] 大佬有考虑过加个能选骰子队的选项吗，这样就能刷指路鳞了 (Issue #126)




 
水月相关功能只为了等级和投资设计
