### ISSUE TITLE
想问下刷指定关卡无法完成是手机问题还是我设置有问题

### ISSUE THREAD

**Issue by SQX779** [tkkcc/arknights#129]
之前怪猎活动的时候输hd-8他会自动定位到hd-6去，然后今天想刷1-7，输入1-7勾选轮次作战之后，速通进入第一章之后开始向右拉屏幕，但是屏幕最右边刚开始出现1-7就会停止拉动，然后判断屏幕中不存在1-7，接着重复两次就自动结束了，想问下这是我个人设置有问题吗

**Comment by tkkcc** [comment]
发录屏

**Comment by SQX779** [comment]
不好意思，速通好像是占用录屏的，本机录屏会失败，只能用愚蠢的拍屏主义了。

文件我拖不上来，我邮箱发你吧

不知道是不是我哪里设置出问题了，看必读里没找到解决办法，只能来这里求助了

**Comment by SQX779** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tkkcc/ArkLights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 晚上9:14
***@***.***&gt;;
抄送:&nbsp;"She‘s ***@***.******@***.***&gt;;
主题:&nbsp;Re: [tkkcc/ArkLights] 想问下刷指定关卡无法完成是手机问题还是我设置有问题 (Issue #129)





 
发录屏
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

IMG_0113.MOV (68.69M, 2023年04月23日 22:37 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=726632364e8184c2a5f7440e476302164b1203005251550d1e045406534e56090b051f03020553145100030f5306550800515300616f30707e216d06505203177e2964365c&code=3f26ac09

**Comment by tkkcc** [comment]
转一下让前置摄像头在左再试试。没用只能套虚拟机app或者换明日计划

**Comment by SQX779** [comment]
好的，谢谢，我去试试
