### ISSUE TITLE
明日方舟速通经常关闭游戏

### ISSUE THREAD

**Issue by SpringWhisper** [tkkcc/arknights#131]
在我自己打开明日方舟后，明日方舟速通总是会关闭游戏，目前我知道以下几种情况：
1.未打开明日方舟速通，等待一段时间后，明日方舟速通会自动启动，同时关闭明日方舟。
2.打开明日方舟速通，但是未运行，等待一段时间后会关闭明日方舟。
3.打开明日方舟速通，点击定时，会立即关闭明日方舟。
4.定时后，手动打开明日方舟，有一定概率在一定时间后关闭明日方舟。

这个问题可以解决吗？

**Comment by tkkcc** [comment]
卸载速通，重启手机可以解决。
