### ISSUE TITLE
更新说明文档telegram api的使用方法

### ISSUE THREAD

**Issue by CaliInn-Li** [tkkcc/arknights#132]
我发现脚本多了一个tg通知功能，但查阅文档后发现文档还没有更新该功能的用法，希望可以有机会得到完善

**Comment by DazeCake** [comment]
@Rovniced

**Comment by Rovniced** [comment]
> 我发现脚本多了一个tg通知功能，但查阅文档后发现文档还没有更新该功能的用法，希望可以有机会得到完善

这周末写吧 tg通知带图片目前还是有问题的

**Comment by Rovniced** [comment]
已经在 #134  中更新
