### ISSUE TITLE
提示根模式错误，程序要么乱跳要么不动

### ISSUE THREAD

**Issue by 15629668505** [tkkcc/arknights#133]
cpu不兼容的处理器具体有哪些？为什么骁龙888也会提示根模式错误

**Comment by tkkcc** [comment]
录屏

**Comment by 15629668505** [comment]
你的脚本不是根据屏幕录制实时分析画面然后来操控的吗，所以假如我要开启录屏的话会和脚本的操作冲突，我的情况不能录下来给你，还有什么其他的解决办法吗

**Comment by tkkcc** [comment]
拍摄

**Comment by 15629668505** [comment]
哦哦，我知道了

**Comment by 15629668505** [comment]
视频太大了发不出来怎么办

**Comment by tkkcc** [comment]
去QQ频道发

**Comment by 15629668505** [comment]
QQ频道在哪里，具体是哪个网站还是论坛吗？

**Comment by tkkcc** [comment]
在必读开头

**Comment by 15629668505** [comment]
好的

**Comment by 15629668505** [comment]
加入频道十五天后才能发言，这怎么办

**Comment by tkkcc** [comment]
传网盘，发分享链接

**Comment by 15629668505** [comment]
等等，我从来没试过，让我研究一下

**Comment by 15629668505** [comment]
上传视频要买个会员，等我操作一下

**Comment by tkkcc** [comment]
阿里云盘

**Comment by 15629668505** [comment]
IMG_1331.MOV
https://www.aliyundrive.com/s/B6f8d6uGMYM
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by 15629668505** [comment]
还需要提供其他信息吗，我的高级设置基本上都没有调过，设定都是程序默认的，不过就算我开启或关闭了一些选项，进入游戏后几乎都是这种情况

**Comment by tkkcc** [comment]
游戏模式，护眼都关。屏幕分辨率与物理分辨率保持一致。还没用只能套虚拟机或者换设备。

**Comment by 15629668505** [comment]
前面几个我都关了，看来只能套虚拟机了，你能不能教教我虚拟机怎么操作？

**Comment by tkkcc** [comment]
安装光速虚拟机，导入游戏和速通，在虚拟机里启动

**Comment by 15629668505** [comment]
谢谢了，咱们明天再聊
