### ISSUE TITLE
老玩家回归会卡住

### ISSUE THREAD

**Issue by djkcyl** [tkkcc/arknights#135]
这个已领取是我手动点的，正常是会一直卡在这儿

![J{FVPO ONYZE7NJM~YRK3JO](https://user-images.githubusercontent.com/59153990/232181759-c5d7c98a-190b-4494-90b3-1dbec29aa6ef.jpg)

**Comment by tkkcc** [comment]
卡10分钟后会有一个处理策略，有等10分钟吗。

**Comment by djkcyl** [comment]
我这边看是卡了2分钟就stop了，然后审判庭里显示已冷却

**Comment by tkkcc** [comment]
已冷却可能是等待后再排队？这个界面在新设备上只有第一次会弹，stop处理会点掉，然后重跑这个号。

**Comment by djkcyl** [comment]
我重启下这个账号试试

**Comment by djkcyl** [comment]
现在又好了，会自动点 x 了，怪

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/232279858-52cd2ea8-11cc-4ec7-8361-be426279852b.png)

![image](https://user-images.githubusercontent.com/59153990/232279794-ec0a9b14-a201-482d-8e8e-8b94c6100632.png)

![image](https://user-images.githubusercontent.com/59153990/232279883-33f8bcad-2228-47ab-b95e-481c1cf2b954.png)
![image](https://user-images.githubusercontent.com/59153990/232279889-6b15b6ad-d4fa-45a1-9d45-93dffce69491.png)


又卡这儿了，第二张图是下面显示了一个stop 120s，没截到图

**Comment by DazeCake** [comment]
> 已冷却可能是等待后再排队？这个界面在新设备上只有第一次会弹，stop处理会点掉，然后重跑这个号。

是同设备第二次登录才不会弹出吗，可能需要审判庭增加一个stop策略，因为正常stop会执行冷却并重新分入等待队列，下一次不一定能分配在同一台设备上

**Comment by tkkcc** [comment]
> 是同设备第二次登录才不会弹出吗

应该是
