### ISSUE TITLE
请求在贸易站屏蔽尤里卡

### ISSUE THREAD

**Issue by Zrief** [tkkcc/arknights#136]
速通似乎只在线索方面屏蔽了尤里卡. 在贸易站仍然考虑了她.

然而尤里卡的贸易站实际效率很低, 
[参考视频](https://www.bilibili.com/video/BV1eV4y1Q7NV?t=127.2)

**Comment by Well2333** [comment]
我发现貌似是速通故意抓尤里卡的，之前看几乎每次都是在第一个贸易站。为了验证这个可能性，刚才我盯着速通看它换班，发现它翻了两页去抓16心情的尤里卡（阈值是12），权重明显高于其他干员效率更高的干员

**Comment by tkkcc** [comment]
贸易站没特别处理。时间是近期的吗，有录屏发出来。 @Well2333

**Comment by Well2333** [comment]
> 贸易站没特别处理。时间是近期的吗，有录屏发出来。 @Well2333 
> 

就在今天下午，~~录屏我稍后补充~~录屏可参考这里，没去还原拖两个屏幕特意去找尤里卡，不过就而结果而言差不多

https://user-images.githubusercontent.com/40534114/233063078-74110b62-e4a2-4536-aaa8-8c7603719f71.mp4

**Comment by tkkcc** [comment]
脚本顶上时间，要是近期的。

**Comment by Well2333** [comment]
> 脚本顶上时间，要是近期的。

录屏已补充，日期为 4.18-22:46

**Comment by tkkcc** [comment]
已更新，日期是今天，看看能不能复现。

**Comment by Well2333** [comment]
> 已更新，日期是今天，看看能不能复现。

已测试，现在贸易站不会选择尤里卡了

**Comment by Zrief** [comment]
可以屏蔽尤里卡了
