### ISSUE TITLE
bug 基建缩放失效

### ISSUE THREAD

**Issue by kaixinseng** [tkkcc/arknights#14]
原本是可以用的，在更新了 缩放修复 后缩放失效 
设备Sony xz1 分辨率1920x1080 Dpi 480 
截图
![Uploading Screenshot_20220319-180150.png…]()

**Comment by tkkcc** [comment]
确认下脚本标题上的时间是15点3分，缩放是否还有问题
之前可用具体是近两天还是近一周

**Comment by kaixinseng** [comment]
> 确认下脚本标题上的时间是15点3分，缩放是否还有问题 之前可用具体是近两天还是近一周

就是最近两天都还是正常

**Comment by tkkcc** [comment]
调了下，看下标题时间是6点的是否有效

**Comment by kaixinseng** [comment]
不行
![Uploading Screenshot_20220319-202131414.jpg…]()

**Comment by tkkcc** [comment]
你发的图我看不到

**Comment by kaixinseng** [comment]
刚刚是用手机传的，可能没成功，我重新发了一份
![bc71e5e35241f91a512d35ca6296593](https://user-images.githubusercontent.com/101924419/159124995-3a6f1a0f-e86b-4bdd-9fb6-5a8d74fdf096.jpg)

**Comment by tkkcc** [comment]
10点的版本 试试看

**Comment by kaixinseng** [comment]
![612285ee7808697feb84947d4dc9706](https://user-images.githubusercontent.com/101924419/159125816-e9bcde01-9ea3-492c-90c8-4688ba92a69b.jpg)
不行

**Comment by tkkcc** [comment]
你虚拟键在左，原因是这个，你把虚拟建调到右边或者关了就行

**Comment by kaixinseng** [comment]
还是不行，我已经用adb关掉了
![8b9c69327a578b34024190656d6e99f](https://user-images.githubusercontent.com/101924419/159126904-e0e0f17b-1f0c-4f0d-9d72-829e4b5a7262.jpg)

**Comment by tkkcc** [comment]
有么有用全面屏手势工具 把左上角留出来 缩放是在左上角滑动的

**Comment by kaixinseng** [comment]
有一个悬浮球，不过我现在也关了，还是这样
![1](https://user-images.githubusercontent.com/101924419/159127565-bc34866f-c7c2-4fa5-b0cf-40dd9a41f11a.png)
![test](https://user-images.githubusercontent.com/101924419/159127576-72baa365-ebe5-4391-9b5c-fe3fbe00b696.png)

**Comment by tkkcc** [comment]
https://user-images.githubusercontent.com/17373509/159152670-36ec020f-3ba9-4d43-a6b7-bd78d431e3eb.mp4


看上面演示，把下面的代码粘贴进调试设置的before_account_hook里，然后在基建界面启动。调整duration和finger直到能基本一次快速缩放到位，然后告诉我。不急。

```lua
-- before_account_hook
local duration = 50
local finger
finger = {
  {point = {{5, 0}}, duration = duration},
  {point = {{0, 0}, {5, 0}}, duration = duration},
}
-- finger = {
--   {point = {{scale(300), scale(200)}}, duration = duration},
--   {point = {{screen.width-scale(300), screen.height-scale(200)}, {scale(300), scale(200)}}, duration = duration},
-- }
-- local w =screen.width//2
-- local h=screen.height//2
-- finger = {
--   {point = {{w-5,h-5}}, duration = duration},
--   {point = {{w+5,h+5}, {w-5,h-5}}, duration = duration},
-- }
gesture(finger)
sleep(duration + 50)


if appear("缩放结束",2) then 
  toast("已找到缩放结束") 
else
  toast("未找到缩放结束") 
end
ssleep(2)
exit()
```

**Comment by kaixinseng** [comment]
我尝试了两种方案 1是启用了原本被注释的代码 2是调整了finger和duration的数值
视频和代码我都上传了（第一个是被注释的，第二个是调整数值的）


https://user-images.githubusercontent.com/101924419/160225529-06a74f8e-237a-4338-be52-e09a7d7b9be6.mp4

[缩放成功 并打开换班的代码.txt](https://github.com/tkkcc/arknights/files/8354698/default.txt)

https://user-images.githubusercontent.com/101924419/160225451-f2bfe4ae-31e6-41d7-8efd-cc042c9dbcaa.mp4

[缩放成功代码.txt](https://github.com/tkkcc/arknights/files/8354699/default.txt)

**Comment by tkkcc** [comment]
https://github.com/tkkcc/arknights/blob/9b46c7962ee1618e47d47c1bbf6c1e4439cad192/util.lua#L1041

暂时没时间改，你可以
清空这个文本框，把链接里整段zoom函数复制进来，修改其中的point与duration，然后启动
像第一种是不行的，会点进去，所以我都用左上角

**Comment by tkkcc** [comment]
可以套vmos用、换设备、换脚本，没必要死磕。

**Comment by kaixinseng** [comment]
ok，谢谢大佬
