### ISSUE TITLE
基建换班老是上尤里卡

### ISSUE THREAD

**Issue by shiyeivu** [tkkcc/arknights#141]
这个干员的基建技能非常差，但是因为默认排在前面，换班的时候老是被排上。建议基建里面把她剔除。

**Comment by tkkcc** [comment]
录屏

**Comment by leo8644** [comment]
是的，还有铎铃也有这个问题。已点star，希望有空的时候能麻烦解决一下。龙门币这样一天会差一万多……

**Comment by Zrief** [comment]
录屏如下

https://user-images.githubusercontent.com/103112786/234286373-77e9080f-28d1-425e-a9e0-bec057ecf5fb.mp4

**Comment by tkkcc** [comment]
提示基建图标异常，说明基建图标不是最新版。已修正。
