### ISSUE TITLE
启动失败：雷电模拟器

### ISSUE THREAD

**Issue by Agnes4m** [tkkcc/arknights#151]
## 截图
打开app，打开权限，点绿色三角启动按钮，则直接弹出停止运行

![image](https://github.com/tkkcc/ArkLights/assets/70925546/a2078ba9-7139-4e4d-b84a-1a501ad2e099)

## 配置

- win10 ，
- 雷电模拟器 9 （64位），
- 1280*720 240dpi，
- 安卓9.0

## 还原错误场景描述

本来是正常的，我记得最后一次启动是水月肉鸽，当时没有关闭脚本直接关闭了模拟器。

之后每次启动都出现这种情况，无法加载多号选择的界面，直接弹出`停止运行`，

## 尝试

重启模拟器等正常手段没发解决，最后没办法只能删除重置app（保存的配置就没了，悲）

**Comment by DazeCake** [comment]
昨天晚上热更新炸了，参考必读里的方式从系统导出配置的json文件，清除数据后再覆写即可，该问题已经修复

**Comment by Agnes4m** [comment]
我如何导出配置json文件?是本地文件浏览吗?

**Comment by DazeCake** [comment]
没错，请参考必读
