### ISSUE TITLE
速通会卡死在公告页

### ISSUE THREAD

**Issue by Yundian1** [tkkcc/arknights#157]
从昨天更新后会出现该问题

![IMG_20230605_200742](https://github.com/tkkcc/ArkLights/assets/84233895/c3e03923-927a-4d39-99a3-686acecf66dc)
![IMG_20230605_200848](https://github.com/tkkcc/ArkLights/assets/84233895/826c7780-278f-4cd5-9c4e-379f3b97368c)

**Comment by Yundian1** [comment]
分辨率 720*1280 dpi320  安卓10

**Comment by tkkcc** [comment]
已修
