### ISSUE TITLE
优化基建换班时存在异格干员的情况

### ISSUE THREAD

**Issue by nullqwertyuiop** [tkkcc/arknights#16]
复现：
1. 使用 `高产` 且脚本运行时已令 `炎熔` 进驻制造站
2. 脚本更换换班时异格干员 `炎狱炎熔` 位于候选位（出现该问题时位于第 7 位）
3. 脚本令异格干员进驻控制室，使制造站出现空缺
4. 后续运行时制造站换班填空回落至极速

预期：
出现异格干员进驻其他单元时自动跳过该干员

**Comment by tkkcc** [comment]
修了，遇到再反馈。
