### ISSUE TITLE
有概率点到换绑页

### ISSUE THREAD

**Issue by Yundian1** [tkkcc/arknights#162]
分辨率1280x720 dpi320
![Screenshot_2023-06-12-21-17-39-827_cn vmos cloudphone](https://github.com/tkkcc/ArkLights/assets/84233895/ec521f48-1046-4704-9b4e-c3019d8dc42d)
![IMG_20230612_211958](https://github.com/tkkcc/ArkLights/assets/84233895/73e0d2e1-d2a2-46e5-ab5e-aed0452d1a07)

**Comment by tkkcc** [comment]
这不是100%吗，录屏看看。而且感觉是重启游戏也没勾。

**Comment by Yundian1** [comment]
并不是100％产生，这台云手机是没有root的，切号通过退出账号重新登陆的方式进行。图中报错是在某次切号的过程中触发换绑页，导致后续账号无法登陆产生的 
或许可以增加一个识别到换绑页返回的功能（？）
