### ISSUE TITLE
官服UI变化，官服账号无法登陆

### ISSUE THREAD

**Issue by chenshan2022** [tkkcc/arknights#166]
官服UI变化，官服账号无法登陆。
官服会在输入账号密码后直接终止该次登陆 判定为失败 跳过账号

**Comment by chenshan2022** [comment]
![image](https://github.com/tkkcc/ArkLights/assets/107569384/acd5a803-fc78-41b9-97a3-4c1ff6a77fc0)

**Comment by chenshan2022** [comment]
设备是雷电云手机,分辨率是720p（320dpi）

**Comment by tkkcc** [comment]
录屏吧

**Comment by chenshan2022** [comment]
https://github.com/tkkcc/ArkLights/assets/107569384/b798ba52-55ed-4679-9574-415375744a48

**Comment by chenshan2022** [comment]
https://github.com/tkkcc/ArkLights/assets/107569384/7a5c21f7-ce44-44fb-89a0-dbe2c3cb75fe

**Comment by tkkcc** [comment]
这个新ui上线几周了，之前也一直登不上？

**Comment by tkkcc** [comment]
@DazeCake 有遇到吗

**Comment by chenshan2022** [comment]
他改回了之前的按钮了
![20230707202411](https://github.com/tkkcc/ArkLights/assets/107569384/d0dbcbb8-a4c6-4e9a-9cbc-efc981ae852a)

**Comment by chenshan2022** [comment]
> 这个新ui上线几周了，之前也一直登不上？

昨天开始  就是这个ui又改回去一点了之后出现了

**Comment by tkkcc** [comment]
这个变成旧ui是账号决定的，还是设备决定的？你可以授权给我，我有空试下

**Comment by chenshan2022** [comment]
> 这个变成旧ui是账号决定的，还是设备决定的？你可以授权给我，我有空试下

只有官服是这样的 B服一切正常  你给我个账号我把雷电云授权给你

**Comment by DazeCake** [comment]
> @DazeCake 有遇到吗

我这还没遇到过

**Comment by tkkcc** [comment]
已fix。现在 “开始唤醒”按钮又有了，会额外判断为一次登录，然后你设的2，所以第一次就认为超了，默认是3是能登上的。现在2也正常。

**Comment by chenshan2022** [comment]
> 已fix。现在 “开始唤醒”按钮又有了，会额外判断为一次登录，然后你设的2，所以第一次就认为超了，默认是3是能登上的。现在2也正常。

感谢大佬
