### ISSUE TITLE
大家都用的什么虚拟机？我的老是崩

### ISSUE THREAD

**Issue by wuyilingwei** [tkkcc/arknights#167]
我以前用vmos，但vmos1.9的某次方舟更新后就来回崩，换了个破解版的光速，但是三天两头虚拟机内部出错。
设备：华为mate10，杀了内置的进程管控

**Comment by by-justin** [comment]
华为我劝你多用

**Comment by wuyilingwei** [comment]
> 华为我劝你多用

这台都是之前淘汰的了，我反正不打算买华为了，但不至于为了挂个速通单独去搞个新手机吧

**Comment by cym31153** [comment]
vmos一般来说比较好吧，vmos不行就光速我用着感觉兼容性比较好，你试试看原版的光速别用破解版的

**Comment by wuyilingwei** [comment]
> vmos一般来说比较好吧，vmos不行就光速我用着感觉兼容性比较好，你试试看原版的光速别用破解版的

有道理，我去试试

**Comment by wuyilingwei** [comment]
> 

谢谢，原版的好不少，大概一周才崩一次
