### ISSUE TITLE
绿野幻梦复刻不能正确识别到活动关

### ISSUE THREAD

**Issue by xinglianqiu5** [tkkcc/arknights#169]
![1689710730179](https://github.com/tkkcc/ArkLights/assets/132866115/9b142832-d0eb-4139-831f-c609563b5831)
进入绿野幻梦-实验基地，无反应，回到主页，然后再进入绿野幻梦-实验基地，无反应，回到主页就执行下一步了

**Comment by xinglianqiu5** [comment]
![f2deadbde74b69ed625514547c3c20a6 00-00-00--00-00-20](https://github.com/tkkcc/ArkLights/assets/132866115/324d77ff-f647-4548-94a9-2a9c431d4779)

**Comment by tkkcc** [comment]
再试试

**Comment by xinglianqiu5** [comment]
可以了
