### ISSUE TITLE
【New Feature】关于自动批量兑换兑换码

### ISSUE THREAD

**Issue by wuyilingwei** [tkkcc/arknights#172]
不太清楚懒人精灵支不支持
我问了下Bing好像是支持post的方法的

登录是https://as.hypergryph.com/user/auth/v1/token_by_phone_password Post
{phone: "xxxx", password: "xxxx"}
会返回一个
{token: "xxxxx"}

礼包地址是https://ak.hypergryph.com/user/api/gift/exchange Post
{giftCode: "00SUMMERCARNIVAL", token: "xxxxxxxxxxxx", channelId: 1}
礼包码可以直接云端下发（00SUMMERCARNIVAL是这次的桃金娘兑换码）

鹰角的token好像是可以直接拿来用的，我试着从通用那个登录那抓了一个（个人界面会跳不好抓），结果是能用的

**Comment by DazeCake** [comment]
没有必要，你可以用任何语言独立实现

**Comment by DazeCake** [comment]
此功能不会添加至速通

**Comment by wuyilingwei** [comment]
> 此功能不会添加至速通

好吧，我感觉这个功能多用户是能用上的（）

**Comment by DazeCake** [comment]
他只有两个http请求，而且相当于都是一次性的，如果要多账号还需要维护每个账号的历史领取状态，频繁的请求登录本身就会导致ip的风控，对于多号的应用场景更是雪上加霜。建议直接用别的语言例如Python的request库实现，只在必要的时候手动本地运行
