### ISSUE TITLE
文档网页不存在

### ISSUE THREAD

**Issue by Agnes4m** [tkkcc/arknights#177]
如图
![image](https://github.com/tkkcc/ArkLights/assets/70925546/b56c14f2-5316-4cce-9b5b-2478ef4786d7)

顺便问问，关卡pr会默认刷第二个大芯片，有没有办法可以让他默认刷第一个小芯片？并不是指定哪一个芯片，而是像pr指令一样随机

**Comment by tkkcc** [comment]
1. 要翻墙
2. pr不随机。pr1
![image](https://github.com/tkkcc/ArkLights/assets/17373509/90842b75-1e8e-44a1-85cf-8c99a31f1b3a)
