### ISSUE TITLE
国际蓝叠模拟器打开应用后显示黑屏

### ISSUE THREAD

**Issue by pointm** [tkkcc/arknights#18]
给予无障碍权限以及其他脚本所有的权限之后，使用分辨率1280x720打开脚本之后屏幕显示黑屏，
![114514](https://user-images.githubusercontent.com/49180699/163706939-1d2f3694-4ff2-456b-8fe1-503c5b9976e3.jpg)
但是使用模拟器的自带截屏功能还能看到内部显示的内容
![Screenshot_2022 04 17_16 29 28 975](https://user-images.githubusercontent.com/49180699/163706981-30bbfb93-88bd-4c94-9e9b-f1daa45249c9.png)
但是外界直接看就看不见对应的内容，是黑屏

**Comment by tkkcc** [comment]
换用高级图形引擎

**Comment by pointm** [comment]
> 换用高级图形引擎

好的👌已解决
