### ISSUE TITLE
关于基建控制中枢

### ISSUE THREAD

**Issue by antidote999** [tkkcc/arknights#21]
能否把老鲤，歌蕾蒂娅这类需要配合的优先度降低，和无法叠加的技能区分一下（例如驴子和诗怀雅）

**Comment by tkkcc** [comment]
[控制中枢选人逻辑
](https://arklights.vercel.app/guide.html#%E6%8E%A7%E5%88%B6%E4%B8%AD%E6%9E%A2%E9%80%89%E4%BA%BA%E9%80%BB%E8%BE%91)

没有降优先级的处理，因为上其他干员可能浪费其他干员在其他站的能力，比如红
