### ISSUE TITLE
账号密码之类的信息会被上传或者被泄漏吗？

### ISSUE THREAD

**Issue by yltx** [tkkcc/arknights#22]
如题  看了一下README 好像没有对相关情况给出说明

**Comment by tkkcc** [comment]
[是否会上传泄漏账号密码
](https://arklights.vercel.app/guide.html#%E6%98%AF%E5%90%A6%E4%BC%9A%E4%B8%8A%E4%BC%A0%E6%B3%84%E6%BC%8F%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81)

**Comment by yltx** [comment]
ok.
