### ISSUE TITLE
关于基建办公室换班

### ISSUE THREAD

**Issue by yltx** [tkkcc/arknights#23]
如题  能否添加对会客室等级的识别  现版本情况下  乌有的排序会低于伊桑之类的 而事实上3级会客室的话乌有的效率反而高于伊桑他们。

（同样的问题还存在于精二的月禾上）

**Comment by tkkcc** [comment]
乌有多5%会客厅，伊桑多5%办公室，这要怎么比。

**Comment by yltx** [comment]
> 乌有多5%会客厅，伊桑多5%办公室，这要怎么比。

不止吧？初始招募位不是2个吗

**Comment by tkkcc** [comment]
乌有多15%会客厅，伊桑多5%办公室，这要怎么比。

**Comment by yltx** [comment]
> 乌有多15%会客厅，伊桑多5%办公室，这要怎么比。

按总效率比啊……

**Comment by tkkcc** [comment]
制造贸易都有1:1.6的差距，这个会客厅和办公室的收益比例有人算过吧？

**Comment by yltx** [comment]
> 制造贸易都有1:1.6的差距，这个会客厅和办公室的收益比例有人算过吧？

这我还真不知道有没有人算过……

**Comment by tkkcc** [comment]
那就别纠结了，按鹰序。

**Comment by yltx** [comment]
> 那就别纠结了，按鹰序。

草 直接开摆是吧

顺便  似乎本脚本不能正常跳转至SN-8和SN-4？

**Comment by tkkcc** [comment]
必读写了。

**Comment by yltx** [comment]
> 必读写了。

看到了  但我实际测试SN-9是可以识别的。

**Comment by tkkcc** [comment]
其他分辨率滑动不准，没再研究。

**Comment by yltx** [comment]
> 其他分辨率滑动不准，没再研究。

彳亍  没事了。
