### ISSUE TITLE
脚本校验失败是怎么一回事啊

### ISSUE THREAD

**Issue by FelixTennouji** [tkkcc/arknights#27]
脚本校验失败是怎么一回事啊
重装直接打不开了

**Comment by Zrief** [comment]
+1，用的是雷电模拟器

**Comment by FelixTennouji** [comment]
> +1，用的是雷电模拟器

我用的是蓝叠hyper-v和vmos两个都不能用，重装提示更新失败，感觉要么是服务器炸了，要么是新版本上传有bug

**Comment by kangkang003** [comment]
+1

**Comment by LUNAR-Q** [comment]
+1，模拟器和实机都测试了，大概率是服务器的问题

**Comment by tkkcc** [comment]
重新下载apk，覆盖安装
