### ISSUE TITLE
点击启动后重启游戏并检测不到开启无障碍服务

### ISSUE THREAD

**Issue by Morris-Lucifer** [tkkcc/arknights#28]
设备及系统：小米10，Android 10
情况描述：
下载前几天发布的apk后卸载了原来已安装的速通助手再安装新的apk，
但是启动后打开所有权限以及无障碍服务，配置好后在游戏主界面启动，程序重启游戏，没过多久手机自动重启。
再次打开速通助手，提示需要打开无障碍服务，且显示关闭，而在设置中无障碍服务都已经设置为速通助手，如何重新设置都不会显示打开，
卸载重装速通助手，手动重启手机仍然会遇到同样的情况，只是不会再自动重启手机了。

**Comment by tkkcc** [comment]
有roo没，有的话把高级设置里禁用acc勾上

**Comment by Morris-Lucifer** [comment]
> 有roo没，有的话把高级设置里禁用acc勾上

root了，禁用后正常了，之前的版本没禁用过所以不知道，谢谢tkkcc
