### ISSUE TITLE
自动更新后高级设置中如何禁用acc

### ISSUE THREAD

**Issue by Morris-Lucifer** [tkkcc/arknights#29]
系统：Android 10（root）
apk版本号：395
安装后给了永久root权限，点击启动后又检测不到已经开启无障碍模式了，之前在关闭的issue中提到可以通过高级设置中禁用acc，但是当前版本好像只能设置重启acc进程间隔

**Comment by tkkcc** [comment]
可以暂时把给速通的root授权关了

**Comment by Morris-Lucifer** [comment]
正常了，再次谢谢tkkcc，：）

**Comment by tkkcc** [comment]
是miui13吗，还是别的。

之前给root情况下，从打开软件点完确定后，到看到作战关卡设置界面的过程中需要手动打开无障碍吗。

**Comment by tkkcc** [comment]
是miui13吗，还是别的。

之前给root情况下，从打开软件点确定，到看到作战关卡设置界面的过程中需要手动打开无障碍吗。

**Comment by Morris-Lucifer** [comment]
是miui 12 20.6.18开发版
今天版本的操作顺序是
0.安装，给通话、存储、悬浮窗等权限，提示需要打开无障碍
1. 打开无障碍模式并不再提醒
2.点确定
3.提示是否给root权限，给了永久
4.配置作战
5.点启动
然后就弹出设置并显示之前打开的无障碍模式检测不到了

**Comment by tkkcc** [comment]
有空可以这样试一下，安装给权限，提示需要无障碍的时候直接点多次蓝色确定按钮，然后会弹是否root授权，给授权，接下来看到的是脚本白色设置界面，还是黑色设置界面？

**Comment by tkkcc** [comment]
是magisk方式root的吗

**Comment by Morris-Lucifer** [comment]
看到的是白色作战设置界面，是以magisk方式root

**Comment by tkkcc** [comment]
然后点启动并定时呢

**Comment by Morris-Lucifer** [comment]
然后就跳转到设置显示无障碍服务没有开启

**Comment by Morris-Lucifer** [comment]
开了也检测不到：（

**Comment by Morris-Lucifer** [comment]
> 看到的是白色作战设置界面，是以magisk方式root

这一步之后如果点击退出并打开设置界面可以看到无障碍显示为开启状态

**Comment by tkkcc** [comment]
magisk和xp模块有什么

**Comment by Morris-Lucifer** [comment]
![Screenshot_2022-05-23-03-19-13-846_org.meowcat.edxposed.manager.jpg](https://user-images.githubusercontent.com/54257509/169712238-4f01b994-f614-4e59-bd0e-3ef6192b4541.jpg)
![IMG_20220523_031838.jpg](https://user-images.githubusercontent.com/54257509/169712244-e5135f65-1952-48c0-bdef-063665e8d16a.jpg)

**Comment by tkkcc** [comment]
好的，没看出问题，你就先不给root用吧。群友试了miui13root的能正常跑。点完启动并定时后，会kill掉自身无障碍进程，然后重启自身无障碍服务，但如果等不到无障碍服务重启成功，就会弹那个。

**Comment by tkkcc** [comment]
脚本日志框里的root_mode是true吗

**Comment by tkkcc** [comment]
我调大了下这里等待无障碍服务重启的时间，标题更新是差不多现在，你以后有空可以试试。

**Comment by Morris-Lucifer** [comment]
> 脚本日志框里的root_mode是true吗

是true，我晚上加群后再试一下吧，刚刚乍一试好像还是不行

**Comment by tkkcc** [comment]
就把禁用重启acc勾着吧。目前只能靠重启acc保持内存稳定。
