### ISSUE TITLE
远程配置功能请求

### ISSUE THREAD

**Issue by DazeCake** [tkkcc/arknights#33]
点佬好，是否有兴趣做一下远程账号配置加载？因为个人觉得多账号的管理有些繁琐，我可以写一套SpringBoot+Mysql的后端API用于管理多账号和配置json载入，可以实现前端账号管理和配置，由速通主动轮询后端服务器来更新配置，不用打开手机进行管理设置效果应该很不错，因为属实是不太会lua没法直接pr，不知意下如何？

**Comment by tkkcc** [comment]
要支持哪些功能，前端谁写。如果只是要远程控制，用[命令行控制](https://arklights.vercel.app/guide.html#%E5%91%BD%E4%BB%A4%E8%A1%8C%E6%8E%A7%E5%88%B6)是否足够。

**Comment by DazeCake** [comment]
前端我可以写
希望支持的功能
- websocket client
- 多账号配置热更新
- 更详细，结构化的通知
- 远程命令行控制

部分云手机厂商不支持命令行控制，可作为备选方案，由后端向速通推送cmd以执行

**Comment by DazeCake** [comment]
开源地址: https://github.com/DazeCake/ArkLightsCloudBackEnd
等写好几个接口后会列个完整的API Doc

**Comment by tkkcc** [comment]
你可以写，我可以负责脚本这块实现，你要定义好协议格式和详细的处理流程。
详细的流程比如获得一个新的多账号配置后，脚本要怎么处理这个新配置，脚本现在正在打剿灭。
websocket client算功能吗。脚本只能get和post，get到与之前不同的信息就执行，post传状态和通知。
我觉得有用的功能，设备状态判定、实时截屏、实时控制，账号增删改查、历史通知、最后一次执行时间。设备异常时短信通知。

**Comment by DazeCake** [comment]
OK，处理流程我明天列个详细的doc给你
ws没有办法实现的话可以轮询心跳实现，返回报文在脚本处理即可
实时控制可能实现有难度，别的功能应该好实现

**Comment by tkkcc** [comment]
实时截屏有一个流量问题，720p截图大概150K，10台设备每10秒获取一次截屏，一天需要`3600*24/10*10*150/1024/1024 = 12GB`。可能需要只在浏览器非空闲时才获取截屏。

**Comment by DazeCake** [comment]
实时截屏应该由前端管理，当admin离线时将不会向后端发送截屏请求

**Comment by DazeCake** [comment]
# 心跳

由于脚本难以实现ws，因此以`get`请求作为心跳包实现轮询通信

## 发送与断线

10s一次，3次断连视为掉线

## 认证

由后端生成唯一`deviceToken`鉴权，心跳包带此参数向服务器表明身份，并携带参数`status`向服务器表示状态

## 响应

响应由2部分组成

- 状态码
- 报文

其中状态码表明程序端应执行的操作，报文内为所需的参数

例如：

状态码 200 报文为空 表示后端未做任何请求，为普通心跳

状态码 201 报文为空 表示程序端因向后端上报当前截图

状态码 1000 报文为一json字符串 表示因立即停止程序端当前所有活动并依据json配置插队执行内容

上述状态码仅为例子，具体要沟通约定一个详细的状态表

# 多账号

多账号由后端进行任务调度和分配

每次程序端对后端`post`请求将会获得一个账号配置，程序端在执行完该账号预定任务后向后端回报完成，后端将会将其标记为完成并等待下一轮加入队列，在此期间程序端掉线或其他异常导致再次请求，后端将会发送之前请求过的账号配置

# 肉鸽

后端将会根据心跳包获取到的程序端信息自动分配空闲服务器作为肉鸽服务器，并向其下发任务

大致流程是这样

**Comment by tkkcc** [comment]
大佬可以的！

**Comment by DazeCake** [comment]
Alpha的API文档将会在[这里](https://github.com/DazeCake/ArkLightsCloudBackEnd/blob/main/docs/Alpha/ArkLightsCloudBackEnd-Alpha-api-docs.md)更新，如果对接口有任何想法与建议欢迎随时与我联系

**Comment by DazeCake** [comment]
# v0.5.2 功能适配请求

[测试服务器](http://123.99.195.109:2000/swagger-ui/index.html#/) 账号：`root` 密码：`123456`

## 停机
接口：`/heartBeat`
描述：返回值`code`为`500`时，立即结束并丢弃当前任务，完成动作后，向`完成停机上报`接口`/haltComplete`请求，返回值`code`为`200`时表示已经同步停机操作，可恢复轮询获取任务接口

## 账号异常处理
[关联issue](https://github.com/AegirTech/Inquisition/issues/3)
接口：`/failTask`
描述：
- 新增`type`类型`accountError`，用于处理所有账号登陆失败问题
- `type`类型`lineBusy`，用于处理账号抢登问题
- `type`类型留空，默认归还任务至等待队列末端

## 日志标准化
示例
```json
{
  "id": 0,
  "level": "INFO",
  "taskType": "daily",
  "title": "[08-13][16:15] 作战报告",
  "detail": "[20分钟] ==> [HD-9]x4 [1-7]x5",
  "imageUrl": "xxx",
  "from": "xxx",
  "server": 0,
  "name": "xxx",
  "account": "xxx",
  "password": "留空，此字段可能会在后期弃用",
  "time": "2022-08-13T16:15:16.844Z",
  "delete": 0
}
```

**Comment by tkkcc** [comment]
> 返回值code为200时表示已经同步停机操作，可恢复轮询获取任务接口

不是200呢

日志标准化是要我按这个格式给你吗，我看只有title和detail需要修改。非作战报告的格式呢。

**Comment by DazeCake** [comment]
不是200的情况只有可能是后端离线，可以30s后重试

日志标准化是希望以一个较为标准的格式来上报日志，旧版的title和detail没有区分

期望的`title`格式：`[MM-dd][HH:mm] 简短的描述内容`

`detail`内容较为不固定，尽可能使用易于分别的半角符号对内容进行分割，非作战报告且无具体内容的可以留空，仅使用`title`即可
