### ISSUE TITLE
获取权限失败

### ISSUE THREAD

**Issue by liyifan687** [tkkcc/arknights#34]
设备：小米平板5 未Root
所有权限都给了，包括无障碍。
但启动软件会弹出 ”获取权限失败，手动授权吗“，这个是需要什么权限？还是设备兼容的问题，谢谢

**Comment by tkkcc** [comment]
手动给权限呢，把能给的都给了。

**Comment by liyifan687** [comment]
@tkkcc 在应用设置页把能给的都给了

**Comment by tkkcc** [comment]
即使能跑，平板分辨率也不支持，要么用明日计划，要么vmos里用速通。
