### ISSUE TITLE
肉鸽能否使用近先队？

### ISSUE THREAD

**Issue by yltx** [tkkcc/arknights#35]
如题   基石只有棘刺   后勤开局的话基本上打不动啊

**Comment by tkkcc** [comment]
打不动什么？

**Comment by yltx** [comment]
> 打不动什么？

打怪打不动啊  棘刺精一只能靠一技能提高输出   会漏一车的吧

**Comment by tkkcc** [comment]
必读里推荐那么多干员你一个都没有？
突击分队+棘刺只会比后勤分队+推荐干员效率更低。

**Comment by yltx** [comment]
行吧    主要是我看着脚本碰到挺多单棘刺应该就能过的关都选择重开挺无语的（
