### ISSUE TITLE
公招建议

### ISSUE THREAD

**Issue by reKelin** [tkkcc/arknights#36]
是否可以支持在没有特殊tag的情况下，选择7时40分进行公招。

**Comment by tkkcc** [comment]
为什么需要

**Comment by reKelin** [comment]
因为有时候（比如刷芯片关或者资源关），不公招完不成当天的任务，在这种情况下可否加一个选项：在没有完成每日任务的情况下公招3次？

**Comment by tkkcc** [comment]
自动招募勾上其他，作战理智不足无法继续时跑1-7，这两个勾了就能做完日常任务。

**Comment by reKelin** [comment]
我想起来了，我当时就是因为勾上其他后是9小时才来问这个的。因为反正也出不了高星，可不可以改成7时40分，保证有3星的情况下省点龙门币

**Comment by Zrief** [comment]
> 我想起来了，我当时就是因为勾上其他后是9小时才来问这个的。因为反正也出不了高星，可不可以改成7时40分，保证有3星的情况下省点龙门币

之前有个小样本的实验, 在无tag情况下, 9小时出四星的概率远大于7时40分. [https://nga.178.com/read.php?tid=23769153](https://nga.178.com/read.php?tid=23769153)
