### ISSUE TITLE
定时任务无法成功执行

### ISSUE THREAD

**Issue by 12dora** [tkkcc/arknights#37]
设备: Google Pixel 2
系统: Android 11 官方系统(已 root) / Lineage OS 19.1(已 root) 
软件版本: 明日方舟速通 v0.0.25 / 明日方舟客户端当前最新
问题表现: 设置定时任务后设备不能在期望时间唤醒，到达设定时间后屏幕点亮，但不能解锁进行后续步骤。手动解锁后可观察到卡在“点确定”界面无法进行下一步，单次手工执行任务可正常完成
其他：1. 标题栏显示时间不正确，小时:分钟 均与本机时间不匹配，也与实际北京时间不匹配，清除缓存，删除脚本重装均无法修正时间
2. 在明日方舟 "尘影余音" 活动前脚本可正常使用
其他条件: 1. 未设置系统密码，上划即可解锁 2. 单次执行脚本时点击锁屏脚本可正常滑动解锁屏幕继续执行
复现率: 使用上述步骤操作必现

**Comment by tkkcc** [comment]
先打开一个别的应用a，再用悬浮按钮启动脚本，使脚本界面悬浮在应用a之上，定时开头写+0，点定时，会停在什么界面。

**Comment by 12dora** [comment]
> 先打开一个别的应用a，再用悬浮按钮启动脚本，使脚本界面悬浮在应用a之上，定时开头写+0，点定时，会停在什么界面。

上述步骤操作会退出该应用，打开 “速通”app，停在确定界面若干秒，然后打开游戏开始执行脚本内容，若点击确定后迅速锁屏则不能自动解锁，会在锁屏界面停留几秒后熄灭，此时点亮屏幕就会出现“点确定”界面

**Comment by tkkcc** [comment]
定时启动遇到锁屏看来有点问题，有空调下。

开发者设置里关掉锁屏就能用吧。

**Comment by 12dora** [comment]
似乎问题出在“不能成功解锁屏幕”，经常只能让息屏显示增亮一下，显示“速通”的通知，然后熄灭。此时如人工点进去是“点确定”界面，稍后会自动执行脚本，但实际上定时场景中会由于无人解锁屏幕导致超时而失败，此时点进去就像卡在“点确定”界面一样。
已测试滑动解锁，录制 pin 解锁，无锁屏（点电源键直接进桌面）三种解锁方式均有极大概率不能进桌面。

**Comment by tkkcc** [comment]
哦对，现在重启时没加亮屏处理，所以那个亮屏只是通知而已。

**Comment by tkkcc** [comment]
调了，试试正常定时有没有用。不要用+0方法定时。

**Comment by 12dora** [comment]
已测试可成功点亮，定时执行恢复正常，感谢开发者改善
