### ISSUE TITLE
蓝叠的支持是否存在问题？

### ISSUE THREAD

**Issue by Orisland** [tkkcc/arknights#39]
蓝叠使用本软件在启动后，会卡在设置的页面，并反复鬼畜按钮打开截图服务。
鬼畜频率相当高。
![image](https://user-images.githubusercontent.com/59354152/176706275-277e0c5f-57a3-4ba2-9d81-63af1af6f949.png)
![image](https://user-images.githubusercontent.com/59354152/176706301-9e50e6dd-513e-4c10-932d-280707db3381.png)

**Comment by tkkcc** [comment]
必读里蓝叠所需设置做了吗

**Comment by Orisland** [comment]
> 必读里蓝叠所需设置做了吗

没注意括号里的小字，感谢回复。

**Comment by tkkcc** [comment]
行了？

**Comment by Orisland** [comment]
> 行了？

是的，在调整为兼容模式后问题解决，非常感谢耐心回复！
