### ISSUE TITLE
蓝叠上出现了较多的问题

### ISSUE THREAD

**Issue by Orisland** [tkkcc/arknights#40]
感觉是模拟器的问题，选关，好友访问，等功能似乎在我这里的运行都不太正常。。
不知道为什么，感觉脚本的识别在我这里运行似乎有很大的问题，之前在mumu上没有出现过(现在由于本地开了hyper-v没有其他模拟器可以选择)。
本地平台，win11，蓝叠5，分辨率720p。
![image](https://user-images.githubusercontent.com/59354152/176733241-0bc19548-ed93-4a5c-9d9a-283dfac80a11.png)

https://user-images.githubusercontent.com/59354152/176732741-e048cb24-bac3-483a-aeab-a42a964dbbe3.mp4

**Comment by tkkcc** [comment]
为什么开坐标

**Comment by Orisland** [comment]
> 为什么开坐标

因为我之前开发app的时候需要知道自己点的位置，于是就一直没有关过，这个在脚本里要求必须关闭吗？

**Comment by tkkcc** [comment]
我不知道

**Comment by Orisland** [comment]
> 我不知道

我没有在readme中找到关闭说明，实测关闭后恢复正常。
如果我没有看漏的话，请作者在脚本的帮助web页面中添加，关闭触摸显示以及坐标显示的说明以减少后续可能出现的类似问题。
如果是因为我个人没有看到通知中的标识，那很抱歉，请无视这条issue。

**Comment by tkkcc** [comment]
没写，因为我也不知道。能用就行。

**Comment by tkkcc** [comment]
蓝叠现在在哪下，是https://www.bluestacks.com/ 吗，能root吗

**Comment by Orisland** [comment]
> 蓝叠现在在哪下，是https://www.bluestacks.com/ 吗，能root吗

是的，可以root，不过不是在界面里root。
你需要手动进入蓝叠的安装目录，修改`bluestacks.conf`文件中的`bst.instance.Nougat64.enable_root_access="1"`，默认值为0，调整为1即可启动root。
不要使用蓝叠X，蓝叠X是网络模拟器，本地需要蓝叠5。

**Comment by tkkcc** [comment]
好的，感谢

**Comment by Orisland** [comment]
https://user-images.githubusercontent.com/59354152/176930616-781aaccf-296c-48ea-9cab-683591425322.mp4


蓝叠上的基建换人似乎出现了一些问题。
该问题目前只出现在宿舍休息轮换模块，其他建筑的轮换没有问题。

**Comment by tkkcc** [comment]
你调了啥，这么慢肯定有问题

**Comment by Orisland** [comment]
> 你调了啥，这么慢肯定有问题

我调整每次选择都等待1.5秒，这是我手动调整的，这个会影响到宿舍换人吗？
![image](https://user-images.githubusercontent.com/59354152/176931517-a3d626a0-b4f3-4437-8b3d-8233f104148d.png)

**Comment by tkkcc** [comment]
必读里写的上限是100

**Comment by Orisland** [comment]
> 必读里写的上限是100



> 必读里写的上限是100

已解决，是我没有读完整readme的问题，抱歉抱歉。
