### ISSUE TITLE
辅助权限与截图服务有概率意外关闭

### ISSUE THREAD

**Issue by 12dora** [tkkcc/arknights#41]
设备: Google Pixel 2
系统:  PixelExperience Android 12 (已 root)
软件版本: 明日方舟速通 v0.0.25 / 明日方舟客户端当前最新
问题表现: 设置定时任务后设备不能在期望时间唤醒，检查发现因不明原因辅助服务与截图权限被关闭，手动解锁后发现卡在“点确定”界面，进入设置发现上述两项必须服务已被关闭，手动重启权限后恢复正常
复现率: 有概率复现
建议：是否可在已 root 设备上自动开启相关权限以防被意外关闭(特别是当设备意外重启后可自动恢复相关权限)

**Comment by tkkcc** [comment]
有通知发下通知。能复现拍一下。

**Comment by 12dora** [comment]
唤醒后视频，请见 https://youtube.com/shorts/yLqEs4xaETc?feature=share
会卡在获取权限页面
如不能访问 ytb，请留言联系方式

**Comment by 12dora** [comment]
上次锁屏时截图权限已正常获取，但下次开屏时权限已丢失(可能因为脚本重启权限释放了)

**Comment by tkkcc** [comment]
再试试能否复现

**Comment by 12dora** [comment]
感谢，重新测试已未见该问题
