### ISSUE TITLE
刷新活动图DV-3无法正确跳转至关卡

### ISSUE THREAD

**Issue by Styx256** [tkkcc/arknights#42]
雷电模拟器，分辨率1080p

**Comment by tkkcc** [comment]
720p可以不，不行用syc

**Comment by LaPluma258** [comment]
同雷电模拟器，也出现了这种情况

**Comment by tkkcc** [comment]
现在呢

**Comment by tkkcc** [comment]
刚调了，不行再open

**Comment by LaPluma258** [comment]
> 
我刷dv7一点启动就直接结束了

**Comment by tkkcc** [comment]
版本多少 @Niubility748

**Comment by LaPluma258** [comment]
> 

蓝奏云下载的最新版

**Comment by tkkcc** [comment]
录屏

**Comment by LaPluma258** [comment]
> 录屏

https://user-images.githubusercontent.com/63944375/177542634-ad11a6c7-cd48-46f0-bd7f-8c51bf6f2460.mp4

**Comment by tkkcc** [comment]
标题更新时间6.21，现在是7月了，开头有提示脚本校验失败。

**Comment by Styx256** [comment]
晚上版本使用已正常

**Comment by Dylan001130** [comment]
蓝叠模拟器，dv-7一启动就结束

**Comment by tkkcc** [comment]
@Dylan001130 录屏反馈

**Comment by Dylan001130** [comment]
> @Dylan001130 录屏反馈

https://user-images.githubusercontent.com/80117781/177791072-0cb6798a-0dc1-4cf1-9a28-7e081ea8b7eb.mp4

蓝叠模拟器，2560*1440分辨率，活动关轮次作战一启动就提示结束，上一次活动没问题。github下载的最新版本。

**Comment by tkkcc** [comment]
@Dylan001130 版本不对，时间还是上个月。把数据清空试试。

**Comment by Dylan001130** [comment]
> @Dylan001130 版本不对，时间还是上个月。把数据清空试试。
可以了，十分感谢！
