### ISSUE TITLE
脚本自动关闭游戏且重启脚本本体

### ISSUE THREAD

**Issue by defEdYs** [tkkcc/arknights#44]
脚本设置为初始设置（开始时为自定义设置 出现问题后重新安装以后仍存在该问题）
设备为红手指KVIP

点击启动or启动并定时后，脚本会运行随机一段时间（有时可持续到一次作战结束 有时刚开始就会出问题）
随后会自动关闭游戏并重启脚本本体，即到达“点确定”界面

经测试 只要运行过一次脚本后即便退出脚本（无侧边悬浮窗状态）只运行游戏 同样会出现该问题（推测为只要脚本在后台运行即会出现此问题）
重启云手机or卸载脚本后则无该问题

**Comment by defEdYs** [comment]
关闭轮次作战 则暂未发现出现该问题的情况

**Comment by tkkcc** [comment]
到达点确定界面，会点击确定，实现重启。为了防止内存泄露。
