### ISSUE TITLE
关于多账号功能

### ISSUE THREAD

**Issue by antidote999** [tkkcc/arknights#45]
本人软件开发小白，若提出无法解决的需求，望谅解，以下是建议。

如果速通输入法导致的无法重启问题无法修复，或许可以增加对多开应用的支持，如国内各大定制rom的多开功能（不过国内定制rom的多开在启动时会有让用户选择的页面，或许脚本可以点击）![IMG_20220711_001754.jpg](https://user-images.githubusercontent.com/76831751/178153032-722ba360-64cd-4e48-b318-608e25a35698.jpg)

亦或是对[炼妖壶island](https://github.com/oasisfeng/island)的支持，island使用[工作资料]以多开，脚本可以增加对工作资料应用的启动功能完成多账号支持（缺点是占用的储存空间会随多开应用的数量增加）

上述两种方法都可以不使用速通输入法进行多账号的托管，在需要修改任务的场景可以省去去系统设置里更换输入法的步骤。

**Comment by tkkcc** [comment]
不能开速通输入法，必读写了。

**Comment by antidote999** [comment]
所以我这不是给的多账号解决方案么🤨

**Comment by tkkcc** [comment]
跟多账号有什么关系

**Comment by antidote999** [comment]
emm就跟官服b服双号双服类似，多开出的应用不需要输入账号密码，就不需要脚本输入法的功能就可以多账号托管

**Comment by tkkcc** [comment]
脚本输入法永远是关的，多账号管理跟输入法没关系

**Comment by tkkcc** [comment]
如果你遇到输入法问题，说明你开了脚本输入法，按必读卸载重装

**Comment by antidote999** [comment]
好的明白了，抱歉打扰，可以close了😥

**Comment by tkkcc** [comment]
再有问题发录屏
