### ISSUE TITLE
反复弹出点确定界面

### ISSUE THREAD

**Issue by shinikiz** [tkkcc/arknights#46]
反复弹出点确定界面以至于无法使用，重装后依然复现。突然就出现了，不知原因。

**Comment by tkkcc** [comment]
录屏

**Comment by shinikiz** [comment]
发现分辨率从1280*720改成1600*900后问题就不出现了，问题也是我把分辨率改成1280*720时开始出现的。

**Comment by tkkcc** [comment]
没有录屏无法解决
