### ISSUE TITLE
关于自动启动

### ISSUE THREAD

**Issue by asukaaal** [tkkcc/arknights#48]
大佬好，我在平时自己打的时候这个app自动启动了，然后明日方舟就重启了，这个是我哪里调错了吗，非常感谢大佬的软件，省了很多时间

**Comment by tkkcc** [comment]
定时了就会自动启动吧。

**Comment by asukaaal** [comment]
没定时，但是现在好了，之前我直接开游戏的，现在我先打开速通app再开游戏就没重启过了，谢谢大佬回复
