### ISSUE TITLE
Bug 云帅云VIP专业版无法正确导航到关卡

### ISSUE THREAD

**Issue by wuyilingwei** [tkkcc/arknights#50]
无法导航的关卡有：1-7，CE，LS
肉鸽似乎工作正常

**Comment by tkkcc** [comment]
云帅云白天性能不足，你可以凌晨再试试。

**Comment by wuyilingwei** [comment]
谢谢，我定个时间
问题是关卡定位似乎是成功的（比如1-7），但是不进入关卡，尝试重新定位。

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tkkcc** [comment]
那你录个屏。我之前用是正常的。看下悬浮按钮是否在左下角。

**Comment by wuyilingwei** [comment]
重复了几次，没有复现成功，大概真的是性能配置的问题？

下次出现时我录下屏，打扰了QWQ
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
发件人: bilabila ***@***.***>
发送时间: 2022年7月21日星期四 下午8:04
收件人: tkkcc/ArkLights
抄送: yige-yigeren; Author
主题: Re: [tkkcc/ArkLights] Bug 云帅云VIP专业版无法正确导航到关卡 (Issue #50)


那你录个屏。我之前用是正常的。

―

**Comment by wuyilingwei** [comment]
> 那你录个屏。我之前用是正常的。看下悬浮按钮是否在左下角。
我先关闭issue了
