### ISSUE TITLE
代理失误后重试失败，脚本直接结束自动作战

### ISSUE THREAD

**Issue by yltx** [tkkcc/arknights#51]
脚本输出：
![](https://s2.loli.net/2022/07/22/ZKCQP9FHVATs8S2.png)

[完整bug触发过程](https://tbs0k-my.sharepoint.com/:v:/g/personal/yltx_tbs0k_onmicrosoft_com/EXJgnJWBMUlJpgjcLTOS45IBeARq0ELkRtBWY8VSv0ZcDA?e=WJuup2)

**Comment by tkkcc** [comment]
![image](https://user-images.githubusercontent.com/17373509/180455759-41b5f1a6-2b1e-4dec-b9cd-824b4275fe2f.png)

这个次数在高级设置里调。

第二次滑动失误的原因是设备性能不足，应该用720p分辨率。

**Comment by yltx** [comment]
> ![image](https://user-images.githubusercontent.com/17373509/180455759-41b5f1a6-2b1e-4dec-b9cd-824b4275fe2f.png)
> 
> 这个次数在高级设置里调。
> 
> 第二次滑动失误的原因是设备性能不足，应该用720p分辨率。

另 在手机上使用时 会卡在输入密码页面不动  相关情况如下：

![6DA406A5DCC33D851BEA21A7BC15C8C4.jpg](https://s2.loli.net/2022/07/22/t8SqdJ6mUGk1RQe.jpg)
![A0E3B0DE013530942C0DA6CF22DB8485.jpg](https://s2.loli.net/2022/07/22/LEITkrhP2HGZseo.jpg)
![55CF5225F0B443DB5B7F84026B2A0A32.jpg](https://s2.loli.net/2022/07/22/tKu8wLmcGB54lNZ.jpg)

视频中有密码部分  不会打码 麻烦给一个联系方式，我私发您。

**Comment by tkkcc** [comment]
![image](https://user-images.githubusercontent.com/17373509/180458877-00169643-96c4-442d-9d68-bad499f43e53.png)

**Comment by yltx** [comment]
> ![image](https://user-images.githubusercontent.com/17373509/180458877-00169643-96c4-442d-9d68-bad499f43e53.png)

设过了 还是不行

**Comment by tkkcc** [comment]
录屏

**Comment by yltx** [comment]
> 录屏

录屏中有密码 给个联系方式我私发

**Comment by tkkcc** [comment]
QQ群群主

**Comment by yltx** [comment]
> QQ群群主

私聊了  何不理我

**Comment by tkkcc** [comment]
what?

**Comment by tkkcc** [comment]
未收到录屏

**Comment by yltx** [comment]
> 未收到录屏

不是qq私聊了吗

**Comment by tkkcc** [comment]
Winter啊

**Comment by yltx** [comment]
> Winter啊

事实上是我推荐我同学用  结果我同学出现了这个问题 因为他没法在github上反馈  我帮他反馈的 winter是我同学

**Comment by tkkcc** [comment]
好的
