### ISSUE TITLE
是否能添加一个美服的方舟速通？

### ISSUE THREAD

**Issue by Roserday** [tkkcc/arknights#52]
rt，请问点点大佬有考虑添加一个美服的吗？

**Comment by tkkcc** [comment]
明日计划能用吗

**Comment by Roserday** [comment]
> 明日计划能用吗

明日计划我去用了下，美服的话只能收收菜，不能像大佬的速通一样基建换人（国服可以换人）。速通的基建换人看着太赏心悦目了，所以想来问问点点大佬有考虑整一个美服的速通吗？

**Comment by tkkcc** [comment]
MAA可以试试。目前没计划。

**Comment by Roserday** [comment]
> MAA可以试试。目前没计划。

好的谢谢大佬的解答，我去看看MAA
