### ISSUE TITLE
能否跳过轮次作战最后的1-7

### ISSUE THREAD

**Issue by Orisland** [tkkcc/arknights#53]
我尝试使用break但是无效，每次活动关打完总会自动打1-7。
打1-7的次数会随着活动关卡需要的理智不同而发生变化，关卡理智门槛越高理智浪费越严重。
例如21理智图打完还有20，那么脚本打完活动关之后，执行的3次1-7就会消耗本应在下个循环使用的理智而产生浪费问题，最终导致代币产出低于预期。同时该问题也会随着脚本的定时周期的缩短而显著上升，我觉得这相当的不好=。=
虽然一开始用1-7兜底避免意外的想法是好的，但是产生的代价我觉得要高于成本。
能否彻底关闭最后的1-7避免这种情况发生？
![image](https://user-images.githubusercontent.com/59354152/181138180-44c68a89-5d4f-43fd-aa9d-6011450eb851.png)
![image](https://user-images.githubusercontent.com/59354152/181138531-9d73f3a8-16f6-4800-9b46-758c53b33b51.png)

**Comment by tkkcc** [comment]
高级设置里关

**Comment by tkkcc** [comment]
break要在做完99次活动才走到，在99次活动中途没理智会去1-7。你不需要break，只需要把1-7设置关了就行。
