### ISSUE TITLE
【bug】定位错误，DH-9，错误定位到剧情关DH-ST-4

### ISSUE THREAD

**Issue by wuyilingwei** [tkkcc/arknights#54]
视频因为超过10M，无法上传，所以上传到[OneDrive](https://yigeyigeren-my.sharepoint.com/:f:/g/personal/yige-yigeren_yigeyigeren_onmicrosoft_com/EgIWj539RzxPkYJnn4irmcMBsLbW6pUxOa0AAfMrOhb2bA?e=aXoilY)
运行设备是云帅云手机，VIP标准版+Root权限补加。
时间是12点过，应该不存在性能问题

**Comment by tkkcc** [comment]
应该1-7都跑不了

**Comment by tkkcc** [comment]
性能不够。用上一次跑，或者换设备换脚本。

**Comment by yige-yigeren** [comment]
有其他的解决办法吗？
比如设置截图最小时间
（目前仅有最小点击时间100ms）

________________________________

**Comment by tkkcc** [comment]
我已经说了3种解决方法

**Comment by tkkcc** [comment]
可以修改代码，让脚本滑动手势支持这台机子。但我说的其他3种解决方法更快。

**Comment by yige-yigeren** [comment]
已经可以了，估计是性能不足，调低点击间隔为200ms，截图为250ms可以有效解决。麻烦了

________________________________
发件人: bilabila ***@***.***>
发送时间: 2022年7月30日星期六 上午9:24
收件人: tkkcc/ArkLights
抄送: yige-yigeren; Author
主题: Re: [tkkcc/ArkLights] 【bug】定位错误，DH-9，错误定位到剧情关DH-ST-4 (Issue #54)


可以修改代码，让脚本滑动手势支持这台机子。但我说的其他3种解决方法更快。

―

**Comment by tkkcc** [comment]
调这种设置会引入很多问题，脚本原来30fps工作的，现在4fps工作。

**Comment by wuyilingwei** [comment]
具体问题找到了，似乎是云帅云在未使用监控时会出错，目前尚不清楚具体原因。（多次更换服务器/重装均无效）
替代解决办法：通过按键精灵持续向云帅云发送按键信息使其强制保持监控状态（10min无操作自动断开）
