### ISSUE TITLE
我能否通过支付现金的方式免除开屏广告？

### ISSUE THREAD

**Issue by Orisland** [tkkcc/arknights#56]
我个人对广告非常反感和讨厌，不过我很乐意为此花一些钱关闭并支持作者。
但是我想确保这些钱直接入作者的账户而不走中间的渠道。
请问作者关闭开屏广告是否可行？
如果这是脚本底层框架而导致的无法跳过的广告，那就没有办法了。

ps：我没有在rm里找到任何类似于支付二维码，爱发电等类似赞助方面的信息，作者没有打算开放这些途径吗？

**Comment by tkkcc** [comment]
最新apk没开屏广告，广告是懒人精灵加的

**Comment by Orisland** [comment]
> 那就只剩一个小问题了，我没有在rm里找到任何类似于支付二维码，爱发电等类似赞助方面的信息，作者没有打算开放这些途径吗？

**Comment by tkkcc** [comment]
目前没有

**Comment by Orisland** [comment]
> 非常感谢作者的答复和慷慨。
