### ISSUE TITLE
[不确定，待观测]当轮次刷图过程中触发大退重启会导致重新计算轮次刷图及吃石头/理智药次数

### ISSUE THREAD

**Issue by zhwe83** [tkkcc/arknights#57]
之前刷的时候就比较奇怪，因为我设定的是一次刷十个石头，但之前都好好的刷完就停止等下一次定时。
但今天偶然登陆发现大退重启后似乎没有继承重启前的刷图次数，重新开始轮次刷图
比较有疑问的就是之前刷的时候似乎没问题，目前猜测是轮次刷图进行完毕后在进行基建操作触发了大退重启，导致重新计算

**Comment by tkkcc** [comment]
正常情况下，脚本能感知到异常，那重启就会存吃药石状态，并且发stop通知。
但在我使用中，多次反复重启后有概率出现状态全清。
我建议吃石头就用1或者99，手动控制，不要相信脚本。

另外，正常基建里不会重启，能复现录屏。
