### ISSUE TITLE
请求增加一个制造站加速什么的设置

### ISSUE THREAD

**Issue by ashesofdream** [tkkcc/arknights#62]
有时候搓玉速度跟不上贸易站要加速一下... 最好能够自动判断是否需要加速搓玉。

**Comment by tkkcc** [comment]
第一个制造站搓玉就会加速。够了就换成其他产品。

**Comment by ashesofdream** [comment]
> 第一个制造站搓玉就会加速。够了就换成其他产品。

比较麻烦 要不就要提前算好需要加速多久，要不就得频繁的换制造站生产什么  
大佬 你或者可以改成 自定义加速几号制造站 这样代码量也不多
