### ISSUE TITLE
有没有办法能兼容到安卓6呀

### ISSUE THREAD

**Issue by plumxxxxxxx** [tkkcc/arknights#63]
用遍了市面的模拟器，发现只有mumu6能开高帧率，其他都模拟器都是锁60，很难受，但是mumu6不支持脚本，现在只能没空的时候开雷电自动刷，想自己玩的时候开mumu

**Comment by tkkcc** [comment]
mumu星云也锁60?

**Comment by plumxxxxxxx** [comment]
是的！我都试了下，发现只有mumu6才能开高帧，星云安卓9也锁60，不知道为啥，其他的雷电蓝叠逍遥都是锁60



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月27日(星期六) 晚上9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tkkcc/ArkLights] 有没有办法能兼容到安卓6呀 (Issue #63)





 
mumu星云也锁60?

**Comment by tkkcc** [comment]
模拟器设置里有的是有高帧率选项的。安卓6不支持无障碍手势，得研究root实现方式，难。

**Comment by plumxxxxxxx** [comment]
那几个模拟器都有高帧率选项只是实际效果达不到，可惜了。问题也不大，我克服一下哈哈哈，麻烦啦，谢谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月27日(星期六) 晚上9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tkkcc/ArkLights] 有没有办法能兼容到安卓6呀 (Issue #63)





 
模拟器设置里有的是有高帧率选项的。安卓6不支持无障碍手势，得研究root实现方式，难。
