### ISSUE TITLE
肉鸽不能用了

### ISSUE THREAD

**Issue by NONGNANG-Lee** [tkkcc/arknights#72]
应该是2022/9/8更新的版本把肉鸽的关卡图给更新了，图像识别不出是哪一关

**Comment by tkkcc** [comment]
录屏

**Comment by NONGNANG-Lee** [comment]
昨晚打不了的，今天开了录屏发现又能打了，昨晚弹出的提示窗意思是无法识别关卡，现在看来好像自己解决了
