### ISSUE TITLE
请问MIUI13平板使用提示“获取权限失败，手动授权吗”如何解决

### ISSUE THREAD

**Issue by Ventofy** [tkkcc/arknights#77]
MIUI13.0.10稳定版，小米平板5p，在开始的环境检测时提示权限失败，让我手动授权，但是也没提示需要什么权限，我就把我看到的权限全部都给了，包括取消了空白通行证，全部都给了最高权限，还是会提示这个问题

**Comment by tkkcc** [comment]
你不是提过issue了吗

**Comment by tkkcc** [comment]
https://github.com/tkkcc/ArkLights/issues/47
