### ISSUE TITLE
源石锭刷取建议

### ISSUE THREAD

**Issue by kermonds** [tkkcc/arknights#8]
Tkkcc，您好：
   在您的”明日方舟速通“中的”其他功能“里的”源石锭刷取“功能，在实际运行中碰到很多次bug，主要是因为第一关打完后，有几率出现4件战利品，导致”什么都不要“选项被覆盖，脚本动弹不得只能重开。
   按照往常思路，此时加宽屏幕就好。但是加宽屏幕后，会出现”礼炮小队“作战关卡，干员实际放置位置偏移导致放不上去的问题。经过长期的测试，最后测明了分辨率在1330*720下，可以快速识别到选项并且放置位置不至于太歪的问题。
   但您是脚本的作者，这边有个提议是在第一关作战完成后，向右滑动屏幕再进行识别。这样就完美了。

**Comment by tkkcc** [comment]
不要了已解，还遇到再反馈（之前是可以的，昨晚我掉快了滑动速度，所以这里就失效了
加宽屏幕导致干员放不上，提供下分辨率信息，我测试下。
第一关作战完成后，向右滑动屏幕再进行识别这句没懂。

**Comment by kermonds** [comment]
![屏幕截图 2022-01-18 171404](https://user-images.githubusercontent.com/49517675/149907976-15ff5bda-5d99-4bcd-bbd8-dfed3a953be2.png)
![屏幕截图 2022-01-18 171405](https://user-images.githubusercontent.com/49517675/149908042-7e2ee5ea-d52c-4f4e-ad40-9358e5db8c1e.png)
我第一次测试的是1440*720，放不上去，在实际位置左上方偏一点

**Comment by tkkcc** [comment]
1440*720放不上干员已修复
不要了界面滑动已修复
有问题请再反馈
