### ISSUE TITLE
关于理智药使用的建议

### ISSUE THREAD

**Issue by reKelin** [tkkcc/arknights#80]
可否将「“x天”理智药最多吃__次」的默认次数设置为0？
之前手机上挂机被坑了一次改了设置，然后模拟器没改，结果模拟器又被坑了
专门为了明天打主线囤的理智药全被吃了，心态崩了啊

**Comment by tkkcc** [comment]
默认设置适用的是任意账号+长期托管。
改成0的话，理智药有浪费风险，不合适。

**Comment by reKelin** [comment]
“快过期”的标准按1-2天算更合适一点吧

**Comment by tkkcc** [comment]
应该是多账号+长期托管，正常一台20个号，月卡一周9个药，1-2天才吃会导致单轮时间远超12小时，从7天开始每轮吃一个才合适。

**Comment by reKelin** [comment]
那必读里可以加粗并解释“快过期理智药”吗，我以为是红底的才算“快过期”的
