### ISSUE TITLE
是否在未来有考虑拆分商业版与个人版？

### ISSUE THREAD

**Issue by Orisland** [tkkcc/arknights#85]
如题。
拆分有利于更好的管理，同样似乎也带来了更大的工作量。
同时对个人版与商业版的相关功能与限制进行明确的划分与说明。
不知道开发者是否有相关的考虑或计划？

**Comment by tkkcc** [comment]
有一个支持水月的不限设备月付版，现在只面向代练巨头，邮箱联系dev@aegirtech.com。
有一个rust重构版还在开发，会尝试付费点。
本仓库维持现有功能正常就差不多了。

**Comment by Orisland** [comment]
> 

rust版有项目地址吗，想去插个眼，如果暂时还不公开那就先不问了。

**Comment by tkkcc** [comment]
没开

**Comment by Orisland** [comment]
> 没开

好吧，那我就先继续等等了。
