### ISSUE TITLE
定时任务截图服务被意外关闭导致执行失败

### ISSUE THREAD

**Issue by 12dora** [tkkcc/arknights#86]
最近经常遇到设置定时任务却不能唤醒的问题, 经检查发现出现该现象时 app 设置中截图服务开关已被关闭(但无障碍服务为开), 需手动打开后才能恢复使用. 截图服务被关闭时状态栏图片亦消失. 目前不知如何锁定该服务使其不被意外关闭, 建议开发者使用 root shell 在每次执行时手动打开或重启该服务
设备: Google Pixel 2
系统: PixelExperience Android 12 (已 root)

**Comment by tkkcc** [comment]
没有贴设置，没有录屏，我也无法复现。本身检测到异常就会重启服务。

**Comment by 12dora** [comment]
设置除'禁用完全重启'外全部为默认(该项不勾选则会卡在点确定). 该问题可能需导出 log, 因为周期极长又可稳定复现(锁屏后只能坚持一天左右正常唤醒), 请教 log 导出方法?

**Comment by tkkcc** [comment]
如果禁用完全重启，就无法重启服务。最简单的解决方法就是上虚拟机或者换个设备。否则就得远程调试了。

**Comment by 12dora** [comment]
降级 Android 11 后问题解决
