### ISSUE TITLE
使用开机自启选项卡时脚本重复单机错误的位置

### ISSUE THREAD

**Issue by Orisland** [tkkcc/arknights#87]
模拟器：雷电
分辨率：1600x900 dpi 240(平板版)

在使用脚本功能，随模拟器启动后自启时，会出现脚本反复单机下图紫框的位置。
![image](https://user-images.githubusercontent.com/59354152/199369689-1f5cf749-85c0-46ad-96a2-6b4ccfc51eb0.png)
![image](https://user-images.githubusercontent.com/59354152/199370215-41705778-c3e0-48a5-b342-7dd74cdb40db.png)

**Comment by DazeCake** [comment]
模拟器请优先使用1080p/720p

**Comment by tkkcc** [comment]
开机自启不支持的，有异常正常
