### ISSUE TITLE
为什么有的时候挂着活动关卡，到最后检查成果的时候，上一次通关显示的是1-7？

### ISSUE THREAD

**Issue by kermonds** [tkkcc/arknights#89]
如题，最近在挂IS-8，但是用此脚本会刷着刷着莫名串到1-7.
我已经检查了相关设置，确认所刷关卡仅填写“上一次”
我已经将软件数据清除，明天等理智回复再行测试。

**Comment by kermonds** [comment]
我自己怀疑是刷了一个月的1-7没清理软件数据软件被我玩坏了

**Comment by tkkcc** [comment]
必读搜“上一次”
