### ISSUE TITLE
叙拉古人活动错误：无法刷第8关

### ISSUE THREAD

**Issue by Agnes4m** [tkkcc/arknights#90]
今天才发现的
指令`IS-9`，`IS-10`都是正常的，但`IS-8`就会失败失败，失败几次后会刷第10关

**Comment by Agnes4m** [comment]
不好意思说错了。，是`IS-9`刷第十关，`IS-8`刷第九关，`IS-7`会失败几次后刷第十关

**Comment by tkkcc** [comment]
最后源石没领
