### ISSUE TITLE
关于云控端的接口对接文档

### ISSUE THREAD

**Issue by qiubai-lab** [tkkcc/arknights#94]
在必读文档中看到对云端对接的支持，由于对lua不是很熟悉所以查看了 `cloud.lua` 部分的代码后还是对云端与速通的 `数据交互的逻辑` 以及 `所需的数据格式规范` 了解的有点模糊，查阅了相关的项目也没有找到对应的文档，不知道大佬有没有补充相关内容文档的计划，方便我们进行云控端的开发。

**Comment by DazeCake** [comment]
云控的http接口可以在部署[审判庭](https://github.com/AegirTech/Inquisition)后访问`http://你的ip:2000/swagger-ui/index.html#/%E4%BB%BB%E5%8A%A1%E6%8E%A5%E5%8F%A3`获取，速通为云控操作抽象了数个接口

- 获取任务
- 任务完成/失败上报
- 日志上报

具体可以查询审判庭 `TaskController`内代码

**Comment by DazeCake** [comment]
哦对了，如果要尝试部署审判庭的话请部署`v0.7.3`，他是一个相对稳定的版本，最近有点忙都没推commit，准备写完了一次性推`v1.0.0`

**Comment by qiubai-lab** [comment]
> 哦对了，如果要尝试部署审判庭的话请部署`v0.7.3`，他是一个相对稳定的版本，最近有点忙都没推commit，准备写完了一次性推`v1.0.0`

感谢大佬回答，审判庭部署是没有什么问题，但是在部署前端的时候发现前端目前处于一个不可用的状态，才回过头去看swagger的接口文档，发现里面的接口参数的含义不是很清晰，所以才提出的这个问题。

**Comment by DazeCake** [comment]
如果是只是想进行云控使用的话可以等待`v1.0.0`，预计在农历年底上线。
如果是想进行二次开发的话就只能读审判庭源码和接口了，接口参数的含义均已用中文标记，至于业务逻辑则需要阅读源码
