### ISSUE TITLE
1080x2400分辨率手机在基建界面卡住

### ISSUE THREAD

**Issue by NONGNANG-Lee** [tkkcc/arknights#95]
发现出现问题的原因是点进基建的任意一个房间，会自动放大一点点视角，退出房间时不能回到最开始的视角，手动缩小可以正常进行下一步，希望可以得到优化谢谢！

**Comment by ZHYANG-2006** [comment]
已收到，这是来自QQ邮箱的假期自动回复邮件。

**Comment by tkkcc** [comment]
跟分辨率无关。真机要完全按必读说明做。

**Comment by NONGNANG-Lee** [comment]
已经严格按照必读说明操作，仍未解决问题，可能是手机问题。手机型号为红米k30u，系统为MIUI13。

**Comment by tkkcc** [comment]
主要是游戏模式 和 游戏模式工具箱 要关，左侧不能有东西，还有虚拟键要在右侧。k40miui13是可以的。实在不行那就是不行。

**Comment by NONGNANG-Lee** [comment]
实在是不行，应该是个别手机会出现的问题。

**Comment by NONGNANG-Lee** [comment]
不影响使用，只要需要缩放的地方手动缩放就能继续运行

**Comment by mingzme** [comment]
我三星 1080*2400也是这样

**Comment by mingzme** [comment]
兄弟你安卓版本你哪个版本，是安卓版本的问题吗？之前我不卡基建，现在卡基建
