### ISSUE TITLE
雷电4闪退报错提示enable snapshot permission by root

### ISSUE THREAD

**Issue by wangKBweb** [tkkcc/arknights#96]
启动以后进入游戏直接闪退 设置里权限全开也无效 报错如图 

![361b3e6360ae7b3ed64f1da2f314306](https://user-images.githubusercontent.com/85718018/214937017-54cd35e7-05d5-40b9-b9b2-d5119150fdff.png)

**Comment by tkkcc** [comment]
内存2G，安卓7。还不行录个屏。
