### ISSUE TITLE
[Feature] 生息演算速刷思路？

### ISSUE THREAD

**Issue by nullqwertyuiop** [tkkcc/arknights#97]
# Source
[Bilibili](https://www.bilibili.com/video/av863505926)

# TL;DR
1. 开局随机选择干员
2. 任意进行战斗节点
3. 开始后直接退出结算
4. 重复操作

**Comment by tkkcc** [comment]
B站很多了，比如这个 https://space.bilibili.com/22172358

**Comment by tkkcc** [comment]
蛋糕加了
