### ISSUE TITLE
如何刷骑兵与猎人GT-5？

### ISSUE THREAD

**Issue by CaliInn-Li** [tkkcc/arknights#98]
无法轮次作战骑兵与猎人GT-5，其他关卡正常

### 脚本设置：
![image](https://user-images.githubusercontent.com/40906144/215934572-1318c34f-3987-49d5-bd7e-7b33ff21b368.png)

开始后脚本就会立刻结束，日志如下：
![image](https://user-images.githubusercontent.com/40906144/215934736-56421ec3-d0b6-46b0-8925-8fb714d8fe58.png)

## 环境：
雷电模拟器9.0.35
![image](https://user-images.githubusercontent.com/40906144/215934791-fcf8ab80-333e-4986-8ac2-65bb0478d134.png)

**Comment by tkkcc** [comment]
没写，要么用 上一次 刷
