### ISSUE TITLE
脚本卡在官服登录界面 [bug]

### ISSUE THREAD

**Issue by AsenHu** [tkkcc/arknights#99]
![Screenshot_20230211_131454_com.huawei.himovie.jpg](https://user-images.githubusercontent.com/78863300/218241567-efeb1ae3-67d0-4295-9c39-b40a35449600.jpg)

![IMG_20230211_130925.jpg](https://user-images.githubusercontent.com/78863300/218241569-8c672594-4dee-490b-b2eb-2d204e748e34.jpg)

![Screenshot_20230211_130747_com.huawei.himovie.jpg](https://user-images.githubusercontent.com/78863300/218241571-25388853-dfd3-49ff-a7d6-0aba8684680d.jpg)

手机系统安卓 11
已授 root 权限

脚本在官服登录时会卡在第三张截图的位置
手动点击账号管理后就正常了
脚本结束后查看日志，发现脚本点击一次账号管理后，就一直想点击账号登录，尽管此时账号管理还没有点下去

**Comment by tkkcc** [comment]
全面屏手势关了吗。如果已经是虚拟键了，高级设置里把点击间隔设成33~100间的数。

**Comment by AsenHu** [comment]
感谢解答，我已经尝试过关闭全面屏了，点击间隔我尝试过 50 75 100 150 毫秒，问题都没有解决。
我目前安装了 vmos，在虚拟机中运行解决了问题
